name: Build Linux

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt update && \
        sudo apt install -y libgtk-4-dev clang
    - name: Build
      run: |
        swift build SwiftCrossUI && \
        swift build GtkBackend && \
        swift build CounterExample && \
        swift build RandomNumberGeneratorExample && \
        swift build WindowPropertiesExample && \
        swift build GreetingGeneratorExample && \
        swift build FileViewerExample && \
        swift build NavigationExample && \
        swift build SplitExample && \
        swift build GtkCodeGen && \
        swift build GtkExample
    - name: Test
      run: swift test
